In [1]:
import sys
import numpy
numpy.set_printoptions(threshold=sys.maxsize)  ## print 생략이 없이 모두 출력

In [2]:
import cv2
img1 = cv2.imread('cat.bmp', cv2.IMREAD_GRAYSCALE)
img2 = cv2.imread('cat.bmp', cv2.IMREAD_COLOR)


In [3]:
img1.shape ## 그레이스케일 영상은 2차원

(480, 640)

In [4]:
img2.shape  ## 컬러영상은 3차원

(480, 640, 3)

In [5]:

# OpenCV 영상 데이터 자료형과 NumPy 자료형

OpenCV 자료형 (1채널) / NumPy / 자료형 구분
---------------------------------------------
cv2.CV_8U / numpy.uint8 8비트 / 부호없는 정수
cv2.CV_8S / numpy.int8 8비트 / 부호있는 정수
cv2.CV_16U / numpy.uint16 16비트 / 부호없는 정수
cv2.CV_16S / numpy.int16 16비트 / 부호있는 정수
cv2.CV_32S / numpy.int32 32비트 / 부호있는 정수
cv2.CV_32F / numpy.float32 32비트 / 부동소수형
cv2.CV_64F / numpy.float64 64비트 / 부동소수형
cv2.CV_16F / numpy.float16 16비트 / 부동소수형


- 그레이스케일 영상: cv2.CV_8UC1 (1채널 의미) → numpy.uint8, shape = (h, w)
- 컬러 영상: cv2.CV_8UC3 (3채널 의미) → numpy.uint8, shape = (h, w, 3)



SyntaxError: invalid syntax (<ipython-input-5-016e682bc2b7>, line 3)

In [7]:
import sys
import cv2


# 영상 불러오기
img1 = cv2.imread('cat.bmp', cv2.IMREAD_GRAYSCALE)
img2 = cv2.imread('cat.bmp', cv2.IMREAD_COLOR)

if img1 is None or img2 is None:
    print('Image load failed!')
    sys.exit()

# 영상의 속성 참조
print('type(img1):', type(img1))
print('img1.shape:', img1.shape)
print('img2.shape:', img2.shape)
print('img1.dtype:', img1.dtype)
print('img2.dtype:', img2.dtype)

# 영상의 크기 참조
h, w = img2.shape[:2]
print('img2 size: {} x {}'.format(w, h))

if len(img1.shape) == 2:
    print('img1 is a grayscale image')
elif len(img1.shape) == 3:
    print('img1 is a truecolor image')

cv2.imshow('img1', img1)
cv2.imshow('img2', img2)
cv2.waitKey()


# 영상의 픽셀 값 참조
#  : for문으로 픽셀 값을 변경하는 작업은 매우 느리므로, 
#    픽셀 값 참조 방법만 확인하고 실제로는 사용 금지

for y in range(h):  ## 480
    for x in range(w):  ## 640
        img1[y, x] = (255)  
        img2[y, x] = (0, 0,255)    ## img2가 imread를 통해 읽어온 값이므로, RGB가 아닌 BGR 형태이다. (RED만 255만큼 출력)     

# img1[:,:] = 255
# img2[:,:] = (0, 0, 255)

cv2.imshow('img1', img1)
cv2.imshow('img2', img2)
cv2.waitKey()

cv2.destroyAllWindows()


type(img1): <class 'numpy.ndarray'>
img1.shape: (480, 640)
img2.shape: (480, 640, 3)
img1.dtype: uint8
img2.dtype: uint8
img2 size: 640 x 480
img1 is a grayscale image


In [ ]:
import numpy as np
import cv2


# 새 영상 생성하기
img1 = np.empty((240, 320), dtype=np.uint8)       # grayscale image,  null값으로 채워넣기 (임의의 갑이 채워짐)
img2 = np.zeros((240, 320, 3), dtype=np.uint8)    # color image (0: 검은색)
img3 = np.ones((240, 320), dtype=np.uint8)*200   # gray scale 그림(2차원), 200값(dark gray)으로 채워넣기
img4 = np.full((240, 320, 3),(0, 255, 255), dtype=np.uint8) # yellow , (240, 320, 3) 차원에 (0, 255, 255) 색상을 full로 채움
print(img4)  # (심, 행, 렬)

# np.full((2, 2), 10)
# -> array([[10, 10],
#         [10, 10]])
# np.full((2, 2), [1, 2])
# -> array([[1, 2],   ## 알아서, 2*2로 만들어 채운다.
#         [1, 2]])


cv2.imshow('img1', img1)
cv2.imshow('img2', img2)
cv2.imshow('img3', img3)
cv2.imshow('img4', img4)
cv2.waitKey()
cv2.destroyAllWindows()

# 영상 복사
img1 = cv2.imread('HappyFish.jpg')

img2 = img1
img3 = img1.copy()

#img1.fill(255)

cv2.imshow('img1', img1)
cv2.imshow('img2', img2)
cv2.imshow('img3', img3)
cv2.waitKey()
cv2.destroyAllWindows()

# 부분 영상 추출
img1 = cv2.imread('HappyFish.jpg')

img2 = img1[40:120, 30:150]  # im2를 변경할경우, im1도 변경됨
img3 = img1[40:120, 30:150].copy()

img2.fill(0)

cv2.imshow('img1', img1)
cv2.imshow('img2', img2)
cv2.imshow('img3', img3)
cv2.waitKey()
cv2.destroyAllWindows()


[[[  0 255 255]
  [  0 255 255]
  [  0 255 255]
  [  0 255 255]
  [  0 255 255]
  [  0 255 255]
  [  0 255 255]
  [  0 255 255]
  [  0 255 255]
  [  0 255 255]
  [  0 255 255]
  [  0 255 255]
  [  0 255 255]
  [  0 255 255]
  [  0 255 255]
  [  0 255 255]
  [  0 255 255]
  [  0 255 255]
  [  0 255 255]
  [  0 255 255]
  [  0 255 255]
  [  0 255 255]
  [  0 255 255]
  [  0 255 255]
  [  0 255 255]
  [  0 255 255]
  [  0 255 255]
  [  0 255 255]
  [  0 255 255]
  [  0 255 255]
  [  0 255 255]
  [  0 255 255]
  [  0 255 255]
  [  0 255 255]
  [  0 255 255]
  [  0 255 255]
  [  0 255 255]
  [  0 255 255]
  [  0 255 255]
  [  0 255 255]
  [  0 255 255]
  [  0 255 255]
  [  0 255 255]
  [  0 255 255]
  [  0 255 255]
  [  0 255 255]
  [  0 255 255]
  [  0 255 255]
  [  0 255 255]
  [  0 255 255]
  [  0 255 255]
  [  0 255 255]
  [  0 255 255]
  [  0 255 255]
  [  0 255 255]
  [  0 255 255]
  [  0 255 255]
  [  0 255 255]
  [  0 255 255]
  [  0 255 255]
  [  0 255 255]
  [  0 255 255]
  [  0 2

In [34]:
###### 영상 화면 반전, numpy 반전 #####

import numpy as np

a = np.arange(15).reshape(3,5)

b= ~a

print(b, b.dtype, sep='\n\n')  ##### int32 타입일 경우에는 반전시 음수 부호가 생김

img_cat = cv2.imread('cat.bmp', cv2.IMREAD_COLOR)

img_cat_rev = ~img_cat  

print(img_cat.dtype, img_cat_rev[0],img_cat[0], sep ='\n\n')

cv2.imshow('img', img_cat_rev)  ##### uint8 타입일 경우에는 반전시   2^8 - 현재값으로 바뀜
cv2.waitKey()

[[ -1  -2  -3  -4  -5]
 [ -6  -7  -8  -9 -10]
 [-11 -12 -13 -14 -15]]

int32
uint8

[[ 64  65  85]
 [ 56  60  79]
 [ 50  54  73]
 [ 41  47  67]
 [ 33  38  60]
 [ 25  31  53]
 [ 20  26  48]
 [ 14  21  39]
 [ 14  20  37]
 [ 16  19  32]
 [ 18  19  31]
 [ 18  18  30]
 [ 17  17  28]
 [ 18  17  31]
 [ 17  17  32]
 [ 21  17  32]
 [ 27  17  33]
 [ 33  18  34]
 [ 42  18  35]
 [ 50  18  36]
 [ 60  17  39]
 [ 70  17  38]
 [ 81  17  36]
 [ 88  17  37]
 [103  16  37]
 [126  14  35]
 [153  11  34]
 [175  11  34]
 [190  10  34]
 [203   8  34]
 [203   8  33]
 [200   7  31]
 [199   6  30]
 [189   6  29]
 [161   9  27]
 [126  11  24]
 [ 98  10  21]
 [ 83  10  19]
 [ 65  10  16]
 [ 52  11  15]
 [ 44  12  15]
 [ 35  11  14]
 [ 25  11  13]
 [ 19  10  12]
 [ 18  10  11]
 [ 17   9  10]
 [ 17   9  10]
 [ 17   9  10]
 [ 16   8   9]
 [ 16   9   9]
 [ 16   9   9]
 [ 16   8   9]
 [ 14   8   9]
 [ 12   7   8]
 [ 12   7   8]
 [  9   7   7]
 [  7   7   7]
 [  6   6   8]
 [  4   5   8]
 [  4   6   9]
 [  3   6   9]
 

-1

In [8]:
##### 마스크연산과 ROI ####
#  * ROI : Region of Interest, 관심영역
#  * 마스크연산 :
#    -OpenCV는일부함수에대해 ROI 연산을지원하며, 이때 마스크영상을 인자로함께 전달해야함 
#     (e.g.) cv2.copyTo(), cv2.calcHist(), cv2.bitwise_or(), cv2.matchTemplate(), etc.
#    -마스크영상은 cv2.CV_8UC1 타입(그레이스케일 영상) 
#    -마스크영상의 픽셀값이 0이아닌 위치에서만 연산이수행됨 → 보통 마스크 영상으로는 0 또는255로 구성된 이진영상(binary image)을 사용


import sys
import cv2


# 마스크 영상을 이용한 영상 합성
src = cv2.imread('airplane.bmp', cv2.IMREAD_COLOR)
mask = cv2.imread('mask_plane.bmp', cv2.IMREAD_GRAYSCALE)
dst = cv2.imread('field.bmp', cv2.IMREAD_COLOR)

if src is None or mask is None or dst is None:
    print('Image load failed!')
    sys.exit()

cv2.copyTo(src, mask, dst)    # dst 파일이 따로 있을경우, 변경
dst2 = cv2.copyTo(src, mask)  # dst 파일이 따로 없을경우, 생성
# dst[mask > 0] = src[mask > 0]
# src, mask, dst는 모두 크기가같아야함. src와dst는 같은 타입이어야하고, mask는 그레이스케일 타입의 이진영상
# - src: 입력영상
# - mask: 마스크영상. 타입은 cv2.CV_8U. (numpy.uint8),  0이 아닌 픽셀에대해서만 복사연산을 수행. 
# - dst: 출력영상. 만약 src와크기 및 타입이같은 dst를 입력으로지정하면 dst를 새로 생성하지않고 연산을수행. 
#        그렇지않으면 dst를 새로생성하여 연산을 수행한후 반환함.

cv2.imshow('src', src)
cv2.imshow('dst', dst)
cv2.imshow('dst2', dst2)
cv2.imshow('mask', mask)
cv2.waitKey(3000)
cv2.destroyAllWindows()




# 알파 채널을 마스크 영상으로 이용
src = cv2.imread('cat.bmp', cv2.IMREAD_COLOR)
logo = cv2.imread('opencv-logo-white.png', cv2.IMREAD_UNCHANGED)
print(logo.shape)  ## 결과 : (222, 180, 4) , RGB가 아닌 'RGBA 또는 RGB + 알파 채널'이 존재하는 영상임 확인됨
                   ## 알파 채널이란, 투명도를 의미함
    
logo_RGBA = cv2.cvtColor(logo, cv2.COLOR_BGRA2RGBA) 
if src is None or logo is None:
    print('Image load failed!')
    sys.exit()

mask = logo_RGBA[:, :, 3]    # mask는 알파 채널로 만든 마스크 영상, 각 픽셀에 대한 BGRA중 A만 입력
# print(mask)

cv2.imshow('mask', mask)
cv2.waitKey()
cv2.destroyAllWindows()

logo = logo[:, :, :-1]# logo는 b, g, r 3채널로 구성된 컬러 영상
h, w = mask.shape[:2]
crop = src[50:50+h, 10:10+w]  # logo, mask와 같은 크기의 부분 영상 추출, 픽셀에서 src[y,x]임을 기억하자

cv2.copyTo(logo, mask, crop)  # crop은 src의 일부분 그 자체이므로, src도 같이 변화됨
#crop[mask > 0] = logo[mask > 0]

cv2.imshow('src', src)
cv2.imshow('logo', logo)
cv2.imshow('mask', mask)
cv2.waitKey()
cv2.destroyAllWindows()


(222, 180, 4)


In [20]:
##### OpenCV 그리기함수 ######


import numpy as np
import cv2

img = np.full((400, 400, 3), (0, 0, 200), np.uint8) ## 흰 그림 만들기


### 직선그리기
# cv2.line(img, pt1, pt2, color, thickness=None, lineType=None, shift=None) -> img
# -img: 그림을 그릴영상 
# -pt1, pt2: 직선의 시작점과 끝점. (x, y) 튜플.
# -color: 선색상 또는 밝기. (B, G, R) 튜플또는 정수값.
# -thickness: 선두께. 기본값은 1. • lineType: 선타입. cv2.LINE_4, cv2.LINE_8, cv2.LINE_AA 중선택. 기본값은 cv2.LINE_8 
# -shift: 그리기 좌표값의 축소비율. 기본값은 0
cv2.line(img, (50, 50), (200, 50), (0, 0, 255), 5)
cv2.line(img, (50, 60), (150, 160), (0, 0, 128))


### 사각형그리기
# cv2.rectangle(img, pt1, pt2, color, thickness=None, lineType=None, shift=None) -> img 
# cv2.rectangle(img, rec, color, thickness=None, lineType=None, shift=None) -> img
# -img: 그림을그릴영상 
# -pt1, pt2: 사각형의두꼭지점좌표. (x, y) 튜플. 
# -rec: 사각형위치정보. (x, y, w, h) 튜플. 
# -color: 선색상또는밝기. (B, G, R) 튜플또는정수값. 
# -thickness: 선두께. 기본값은 1. 음수(-1)를 지정하면내부를채움. 
# -lineType: 선타입. cv2.LINE_4, cv2.LINE_8, cv2.LINE_AA 중선택. 기본값은 cv2.LINE_8 
# -shift: 그리기좌표값의축소비율. 기본값은 0
cv2.rectangle(img, (50, 200, 150, 100), (0, 255, 0), 2)  ## -rec: 사각형위치 정보. (x, y, w, h) 튜플 적용
cv2.rectangle(img, (70, 220), (180, 280), (0, 128, 0), -1)  ## -pt1, pt2: 사각형의 두 꼭지점 좌표. (x, y) 튜플 적용


### 원 그리기
# cv2.circle(img, center, radius, color, thickness=None, lineType=None, shift=None) -> img
# - thickness: 선두께. 기본값은 1. 음수(-1)를 지정하면 내부를 채움
cv2.circle(img, (300, 100), 30, (255, 255, 0), -1, cv2.LINE_AA)   ## 내부 채움 적용
cv2.circle(img, (300, 100), 60, (255, 0, 0), 3, cv2.LINE_AA)

           
### 다각형 그리기
# cv2.polylines(img, pts, isClosed, color, thickness=None, lineType=None, shift=None) -> img
# -pts: 다각형외곽점들의좌표배열. numpy.ndarray의리스트. (e.g.) [np.array([[10, 10], [50, 50], [10, 50]], dtype=np.int32)] 
# -isClosed: 폐곡선여부. True 또는 False 지정. • color: 선색상또는밝기. (B, G, R) 튜플또는정수값. 
# -thickness: 선두께. 기본값은 1. 음수(-1)를 지정하면내부를채움. 
pts = np.array([[250, 200], [300, 200], [350, 300], [250, 300]])
cv2.polylines(img, [pts], True, (255, 0, 255), 2)


### 문자열 출력
# cv2.putText(img, text, org, fontFace, fontScale, color, thickness=None, lineType=None, bottomLeftOrigin=None) -> img
# -img: 그림을그릴영상 
# -text: 출력할문자열 
# -org: 영상에서문자열을출력할위치의좌측하단좌표. (x, y) 튜플. 
# -fontFace: 폰트종류. cv2.FONT_HERSHEY_ 로시작하는상수중선택 
# -fontScale: 폰트크기확대/축소비율 • color: 선색상또는밝기. (B, G, R) 튜플또는정수값. 
# -thickness: 선두께. 기본값은 1. 음수(-1)를 지정하면내부를채움. 
# -lineType: 선타입. cv2.LINE_4, cv2.LINE_8, cv2.LINE_AA 중선택. 
# -bottomLeftOrigin: True이면영상의좌측하단을원점으로간주. 기본값은 False.  -> True이면 문자가 위아래 반전된다.

text = 'Hello? OpenCV ' + cv2.__version__
cv2.putText(img, text, (50, 350), cv2.FONT_HERSHEY_SIMPLEX, 0.8, 
            (0, 0, 255), 1, cv2.LINE_AA, bottomLeftOrigin = True) 

cv2.imshow("img", img)

cv2.waitKey()
cv2.destroyAllWindows()



In [ ]:
############# 카메라와동영상처리하기 1 ##############
#  - cv2.VideoCapture 클래스 
#    : OpenCV에서는카메라와 동영상으로부터 프레임(frame)을 받아오는작업을 cv2.VideoCapture 클래스하나로처리함


##### 카메라 다루기 ######

import sys
import cv2


# 카메라 열기
cap = cv2.VideoCapture(0)

if not cap.isOpened():
    print("Camera open failed!")
    sys.exit()

# 카메라 프레임 크기 출력
print('Frame width:', int(cap.get(cv2.CAP_PROP_FRAME_WIDTH)))
print('Frame height:', int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT)))

# 카메라 프레임 처리
while True:
    ret, frame = cap.read()

    if not ret:
        break

    inversed = ~frame  # 반전

    cv2.imshow('frame', frame)
    cv2.imshow('inversed', inversed)

    if cv2.waitKey(10) == 27:
        break

cap.release()
cv2.destroyAllWindows()



In [35]:
############# 카메라와동영상처리하기 1 ##############
#  - cv2.VideoCapture 클래스 
#    : OpenCV에서는카메라와 동영상으로부터 프레임(frame)을 받아오는작업을 cv2.VideoCapture 클래스하나로처리함


##### 동영상 feature 확인 : cv2.VideoCapture.get() ######


import sys
import cv2


# 비디오 파일 열기
cap = cv2.VideoCapture('video1.mp4')

if not cap.isOpened():
    print("Video open failed!")
    sys.exit()

# 비디오 프레임 크기, 전체 프레임수, FPS 등 출력
# : cv2.VideoCapture.get(propId) 
# - propId: 속성상수. (OpenCV 문서참조)
#     CAP_PROP_FRAME_WIDTH 프레임가로크기 
#     CAP_PROP_FRAME_HEIGHT 프레임세로크기 
#     CAP_PROP_FPS 초당프레임수 
#     CAP_PROP_FRAME_COUNT 비디오파일의 총프레임수
#     CAP_PROP_POS_MSEC 밀리초단위로 현재위치 
#     CAP_PROP_POS_FRAMES 현재 프레임번호 
#     CAP_PROP_EXPOSURE 노출
# - retval: 성공하면 해당속성값, 실패하면 0.

print('Frame width:', int(cap.get(cv2.CAP_PROP_FRAME_WIDTH)))
print('Frame height:', int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT)))
print('Frame count:', int(cap.get(cv2.CAP_PROP_FRAME_COUNT)))
print('Frame per sec(FPS):', int(cap.get(cv2.CAP_PROP_FPS)))


fps = cap.get(cv2.CAP_PROP_FPS) ## FPS 저장

delay = round(1000 / fps)   ## FPS의 역수 = 프레임당 시간





##### 동영상 입력 다루기 : cv2.VideoCapture.read ######

# 비디오 매 프레임 처리
while True:
  
  ##### 프레임 받아오기 #####
  # cv2.VideoCapture.read(image=None) -> retval: 성공여부(성공이 True), image: 현재 프레임(numpy.ndarray)
    ret, frame = cap.read()

    if not ret:
        break

    inversed = ~ frame  # 영상 반전

    cv2.imshow('frame', frame)
    cv2.imshow('inversed', inversed)

    if cv2.waitKey(delay) == 27:
        break

cap.release()
cv2.destroyAllWindows()

Frame width: 1280
Frame height: 720
Frame count: 85
Frame per sec(FPS): 24


In [36]:
############# 카메라와동영상처리하기 1 ##############
#  - cv2.VideoCapture 클래스 
#    : OpenCV에서는카메라와 동영상으로부터 프레임(frame)을 받아오는작업을 cv2.VideoCapture 클래스하나로처리함


##### 동영상 출력 다루기 : cv2.VideoWriter ######


import sys
import cv2


cap = cv2.VideoCapture('video1.mp4')

if not cap.isOpened():
    print("Camera open failed!")
    sys.exit()

w = round(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
h = round(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
fps = cap.get(cv2.CAP_PROP_FPS)


### cv2.VideoWriter 클래스  
# - OpenCV에서는 cv2.VideoWriter 클래스를 이용하여 일련의 프레임을 동영상 파일로 저장할수있음 
# - 일련의 프레임은 모두크기와 데이터 타입이 같아야함
## cv2.VideoWriter(filename, fourcc, fps, frameSize, isColor=None) -> retval
    # frameSize: 프레임크기. (width, height) 튜플
    # fourcc(문자코드)
    # -cv2.VideoWriter_fourcc(*'DIVX') DIVX MPEG-4  코덱 
    # -cv2.VideoWriter_fourcc(*'XVID') XVID MPEG-4  코덱 
    # -cv2.VideoWriter_fourcc(*'FMP4') FFMPEG MPEG-4  코덱 
    # -cv2.VideoWriter_fourcc(*'X264') H.264/AVC 코덱 
    # -cv2.VideoWriter_fourcc(*'MJPG') Motion-JPEG 코덱

fourcc = cv2.VideoWriter_fourcc(*'DIVX') # *'DIVX' == 'D', 'I', 'V', 'X'
delay = round(1000 / fps)

out = cv2.VideoWriter('output.avi', fourcc, fps, (w, h))  ### 저장을 위한 세팅 완료

if not out.isOpened():
    print('File open failed!')
    cap.release()
    sys.exit()

while True:
    ret, frame = cap.read()

    if not ret:
        break

    inversed = ~frame

    out.write(inversed)     ### 프레임을 동영상으로 저장, cv2.VideoWriter('output.avi', fourcc, fps, (w, h)).write(프레임)
                            ### 여기서는 반전된 프레임을 저장하고 있음

    cv2.imshow('frame', frame)
    cv2.imshow('inversed', inversed)

    if cv2.waitKey(delay) == 27:
        break

cap.release()
out.release()
cv2.destroyAllWindows()


In [37]:
############  연산시간 측정  ###############
# : 컴퓨터비전은대용량데이터를다루고, 일련의과정을통해최종결과를 얻으므로매단계에서연산시간을측정하여관리할필요가있음
# : OpenCV에서는 TickMeter 클래스를 이용하여 연산시간을 측정

# cv2.TickMeter() -> tm
# - tm: cv2.TickMeter 객체
# - tm.start(): 시간측정시작 
# - tm.stop(): 시간측정끝
# - tm.reset(): 시간측정초기화
# - tm.getTimeSec(): 측정시간을초단위로반환
# - tm.getTimeMilli(): 측정시간을밀리초단위로반환
# - tm.getTimeMicro(): 측정시간을마이크로초단위로반환

### 예제 ###
img = cv2.imread('hongkong.jpg')

tm = cv2.TickMeter() 
 
tm.start()                       ## 측정 시작
edge = cv2.Canny(img, 50, 150)   ## 해당 코드에 대해서 time 측정
tm.stop()                        ## 측정 끝

print('Elapsed time: {}ms.'.format(tm.getTimeMilli()))


Elapsed time: 125.47530000000002ms.


In [45]:
########## 동영상 전환 effect ##############
#  동영상전환이펙트 : 
# -  두 동영상 클립 사이에 추가되는 애니메이션 효과 
# -  페이드-인(fade-in), 페이드-아웃(fade-out), 디졸브(dissolve), 밀기, 확대

# 구현할기능 :
# - 두 개의 동영상 동시 열기 
# - 첫번째 동영상의 마지막 N개프레임과 두번째 동영상의 처음 N개 프레임을 합성 
# - 합성된 영상을 동영상으로 저장하기




import sys
import numpy as np
import cv2


# 두 개의 동영상을 열어서 cap1, cap2로 지정
cap1 = cv2.VideoCapture('video1.mp4')
cap2 = cv2.VideoCapture('video2.mp4')

if not cap1.isOpened() or not cap2.isOpened():
    print('video open failed!')
    sys.exit()

# 두 동영상의 크기, FPS는 같다고 가정함
frame_cnt1 = round(cap1.get(cv2.CAP_PROP_FRAME_COUNT))
frame_cnt2 = round(cap2.get(cv2.CAP_PROP_FRAME_COUNT))
fps = cap1.get(cv2.CAP_PROP_FPS)
effect_frames = int(fps * 2)  ## fps를 2배로 상승

print('frame_cnt1:', frame_cnt1)
print('frame_cnt2:', frame_cnt2)
print('FPS:', fps)            ## fps는 둘 다 같다고 가정


delay = int(1000 / fps)

w = round(cap1.get(cv2.CAP_PROP_FRAME_WIDTH))
h = round(cap1.get(cv2.CAP_PROP_FRAME_HEIGHT))
fourcc = cv2.VideoWriter_fourcc(*'DIVX')
print('frame_width:', w)
print('frame_height:', h)

# 출력 동영상 객체 생성
out = cv2.VideoWriter('output.avi', fourcc, fps, (w, h))

# 1번 동영상 복사
for i in range(frame_cnt1 - effect_frames): ## 동영상 뒤쪽 2초간(페이트 in/out 된 시간) frame만큼 제외하고, 복사
    ret1, frame1 = cap1.read()

    if not ret1:
        print('frame read error!')
        sys.exit()

    out.write(frame1)
    print('.', end='')

    cv2.imshow('output', frame1)
    cv2.waitKey(delay)

# 1번 동영상 뒷부분과 2번 동영상 앞부분을 합성
for i in range(effect_frames):           ## 2초간, 페이드 in, 페이드 out 실행
    ret1, frame1 = cap1.read()
    ret2, frame2 = cap2.read()

    if not ret1 or not ret2:
        print('frame read error!')
        sys.exit()

    dx = int(w / effect_frames) * i        ## 페이드 in, 페이드 out 할만큼의 width를 설정  (프레임 당)

    frame = np.zeros((h, w, 3), dtype=np.uint8)
    frame[:, 0:dx, :] = frame2[:, 0:dx, :]   ## 동영상 1의 영상은 0부터 dx까지
    frame[:, dx:w, :] = frame1[:, dx:w, :]   ## 동영상 2의 영상은 dx부터 끝까지 복사하여 붙인다.

    #alpha = i / effect_frames
    #frame = cv2.addWeighted(frame1, 1 - alpha, frame2, alpha, 0)

    out.write(frame)
    print('.', end='')

    cv2.imshow('output', frame)
    cv2.waitKey(delay)

# 2번 동영상을 복사
for i in range(effect_frames, frame_cnt2):  ### 페이드 in/out 된 시간만큼(2초)을 제외하고 복사
    ret2, frame2 = cap2.read()

    if not ret2:
        print('frame read error!')
        sys.exit()

    out.write(frame2)
    print('.', end='')

    cv2.imshow('output', frame2)
    cv2.waitKey(delay)

print('\noutput.avi file is successfully generated!')

cap1.release()
cap2.release()
out.release()
cv2.destroyAllWindows()



frame_cnt1: 85
frame_cnt2: 121
FPS: 24.0
frame_width: 1280
frame_height: 720
......................................................................................................................................
output.avi file is successfully generated!
