# CNN 학습 실습

## Import modules

In [2]:
# https://deep-eye.tistory.com/41

import tensorflow as tf

# tf.python.control_flow_ops = tf
import numpy as np
import pandas as pd
import sys

from tensorflow.keras.layers import Conv2D, MaxPool2D, Flatten, Dense
from tensorflow.keras.models import Sequential
from tensorflow.python.keras.applications.vgg16 import VGG16
from tensorflow.python.keras.preprocessing.image import ImageDataGenerator
from tensorflow.python.keras.layers import Conv2D, MaxPooling2D, Flatten
from tensorflow.python.keras.layers import Dense, Dropout, Input
from tensorflow.python.keras.models import Model

from torchvision import transforms
from PIL import Image
import matplotlib.pyplot as plt

np.set_printoptions(threshold=sys.maxsize)
pd.set_option('display.max_rows', None)

In [ ]:
# 사전 학습된 모델 불러오기
input_tensor = Input(shape=(150,150,3))
model = VGG16(weights='imagenet', include_top=False, input_tensor = input_tensor)

# 모델 Layer 데이터화
layer_dict = dict([(layer.name, layer) for layer in model.layers])

# Layer 추가
x = layer_dict['block5_pool'].output
# Cov2D Layer +
x = Conv2D(filters = 64, kernel_size=(3, 3), activation='relu')(x)
# MaxPooling2D Layer +
x = MaxPooling2D(pool_size=(2, 2))(x)
# Flatten Layer +
x = Flatten()(x)
# FC Layer +
x = Dense(2048, activation='relu')(x)
x = Dropout(0.5)(x)
x = Dense(1024, activation='relu')(x)
x = Dropout(0.5)(x)
x = Dense(2, activation='softmax')(x)

# new model 정의
new_model = Model(inputs = model.input, outputs = x)

In [ ]:
# CNN Pre-trained 가중치를 그대로 사용할때
for layer in new_model.layers[:19] :
    layer.trainable = False

new_model.summary()

# 컴파일 옵션
new_model.compile(loss='sparse_categorical_crossentropy',
                     optimizer='adam',
                     metrics=['accuracy'])

In [ ]:
# 모델 학습
history = new_model.fit(train_data_gen, epochs=5,
                        validation_data=test_data_gen)

## 하이퍼파라미터 정의

In [172]:
EPOCHS = 200

In [173]:
k = np.arange(12)

k = k.reshape(3,4,1)
k

array([[[ 0],
        [ 1],
        [ 2],
        [ 3]],

       [[ 4],
        [ 5],
        [ 6],
        [ 7]],

       [[ 8],
        [ 9],
        [10],
        [11]]])

## 네트워크 구조 정의

In [185]:
# mnist = input_data.read_data_sets('./MNIST_data/', one_hot=True)


np.set_printoptions(threshold=sys.maxsize)
pd.set_option('display.max_rows', None)

# train_df = pd.read_csv(r'D:\대회\Mnist 손글씨 분류 경진대회\dataset\train\train_data.csv')
# train_dir = r'D:\대회\Mnist 손글씨 분류 경진대회\dataset\train\\'
train_df = pd.read_csv(r'C:\Users\6509504\Mnist_number\dataset\train\train_data.csv')
train_dir = r'C:\Users\6509504\Mnist_number\dataset\train\\'
train_file_path = train_dir + train_df['file_name']

    
def dataset_raw (path):
    
    image = Image.open(path) 
    image_array = np.array(image).reshape(28,28,1)#.reshape(784)
    return image_array

def dataset_rotation30 (path):
    
    rotation30 = transforms.RandomRotation(30)
    image = Image.open(path)
    image = rotation30(image)
    image_array = np.array(image).reshape(28,28,1)#.reshape(784)
    return image_array

def dataset_rotation40 (path):
    
    rotation30 = transforms.RandomRotation(30)
    image = Image.open(path)
    image = rotation30(image)
    image_array = np.array(image).reshape(28,28,1)#.reshape(784)
    return image_array


def dataset_crop (path):
    
    crop = transforms.CenterCrop(12)
    image = Image.open(path)
    image = crop(image)
    image_array = np.array(image).reshape(28,28,1) #.reshape(784)
    return image_array


def dataset_erase (path):
    
    erase = transforms.Compose([transforms.PILToTensor(),transforms.RandomErasing(0.5),transforms.ToPILImage() ])
    image = Image.open(path)
    image = erase(image)
    image_array = np.array(image).reshape(28,28,1)#.reshape(784)
    return image_array

# train_label = np.array(pd.get_dummies(train_df['label']))
train_label = np.array(train_df['label'])
print(train_label)

train_data_raw = np.array(list(train_file_path.apply(dataset_raw)), dtype='float32')
train_data_r30 = np.array(list(train_file_path.apply(dataset_rotation30)), dtype='float32')
train_data_r40 = np.array(list(train_file_path.apply(dataset_rotation40)), dtype='float32')
# train_data_crop = np.array(list(train_file_path.apply(dataset_crop)), dtype='float32')
train_data_erase = np.array(list(train_file_path.apply(dataset_erase)), dtype='float32')


train_data = np.vstack([train_data_raw, train_data_r30, train_data_r40, train_data_erase]) 
train_label = np.hstack([train_label, train_label, train_label, train_label]) 

[8 8 8 8 8 8 8 8 8 8 9 8 9 9 8 8 9 9 9 8 8 8 9 9 8 9 9 9 8 8 9 9 8 8 8 8 8
 8 8 8 9 8 9 8 9 9 8 8 9 8 8 8 8 9 9 9 9 9 9 9 8 8 9 9 8 9 8 8 8 9 9 9 9 8
 9 9 9 9 9 9 9 9 9 8 8 9 9 9 9 9 8 8 9 8 8 9 9 8 8 8 9 8 8 9 8 8 9 9 9 9 8
 8 9 8 8 9 8 9 9 8 8 9 8 9 9 8 9 8 8 8 8 8 9 9 8 9 8 8 8 9 9 8 8 9 8 8 8 9
 9 8 8 8 8 8 9 8 8 8 8 9 9 9 9 8 9 9 9 9 9 9 9 8 8 9 8 9 9 9 9 9 9 9 9 8 9
 8 9 9 9 9 9 8 8 9 8 8 9 8 9 8 9 9 9 2 8 2 8 2 8 8 8 9 8 9 8 2 8 8 2 8 9 2
 7 9 7 2 2 8 8 8 7 8 8 7 9 7 8 8 9 2 9 7 9 2 7 8 9 7 2 2 2 8 7 7 2 8 9 9 2
 3 3 7 2 8 8 9 3 2 2 2 7 7 2 2 3 9 7 8 7 8 8 2 2 7 9 2 7 3 9 9 3 9 7 8 9 8
 7 8 8 7 9 9 3 9 8 3 3 2 9 7 2 9 2 9 3 7 3 7 3 3 2 9 8 3 2 7 8 9 2 3 8 7 2
 9 9 9 9 8 9 8 8 8 7 9 9 7 3 2 2 3 3 2 7 9 8 9 7 8 9 3 3 2 8 8 9 7 3 7 8 2
 3 2 9 8 7 2 9 7 2 2 9 2 8 8 7 8 3 8 2 9 2 3 8 9 7 8 2 9 2 2 3 8 3 9 9 3 9
 7 3 2 9 2 8 9 7 7 7 8 7 2 7 9 7 2 9 2 3 9 2 2 7 3 7 7 7 2 8 7 9 9 7 7 2 8
 9 8 2 7 2 7 3 2 3 7 3 3 8 2 9 3 7 3 3 3 7 2 7 9 8 2 2 7 9 3 8 8 7 2 3 8 8
 2 2 2 2 2 2 2 7 2 7 8 8 

In [186]:
def MyModel():
    return Sequential([Conv2D(32, (3, 3), padding='same', activation='relu'), # 28x28x32
                       MaxPool2D(), # 14x14x32
                       Conv2D(64, (3, 3), padding='same', activation='relu'), # 14x14x64
                       MaxPool2D(), # 7x7x64
                       Conv2D(128, (3, 3), padding='same', activation='relu'), # 7x7x128
                       Flatten(), # 6272
                       Dense(128, activation='relu'),
                       Dense(10, activation='softmax')]) # 128

In [187]:
x_train = train_data.copy()
y_train = train_label.copy()
print(x_train.shape)
print(y_train.shape)

(20000, 28, 28, 1)
(20000,)


## 데이터 불러오기

In [188]:
# fashion_mnist = tf.keras.datasets.fashion_mnist

# class_names = ['T-shirt/top', 'Trouser', 'Pullover', 'Dress', 'Coat',
#                'Sandal', 'Shirt', 'Sneaker', 'Bag', 'Ankle boot']

# (x_train, y_train), (x_test, y_test) = fashion_mnist.load_data()
# x_train, x_test = x_train / 255.0, x_test / 255.0

# x_train = x_train.astype(np.float32)
# x_test = x_test.astype(np.float32)

# # NHWC
# x_train = x_train[..., np.newaxis]
# x_test = x_test[..., np.newaxis]

train_ds = tf.data.Dataset.from_tensor_slices((x_train, y_train)).shuffle(10000).batch(32).prefetch(2048)
# test_ds = tf.data.Dataset.from_tensor_slices((x_test, y_test)).batch(32).prefetch(2048)

In [189]:
for a, b in train_ds.take(1):
    print(a,b)

tf.Tensor(
[[[[  0.]
   [  0.]
   [  0.]
   [  0.]
   [  0.]
   [  0.]
   [  0.]
   [  0.]
   [  0.]
   [  0.]
   [  0.]
   [  0.]
   [  0.]
   [  0.]
   [  0.]
   [  0.]
   [  0.]
   [  0.]
   [  0.]
   [  0.]
   [  0.]
   [  0.]
   [  0.]
   [  0.]
   [  0.]
   [  0.]
   [  0.]
   [  0.]]

  [[  0.]
   [  0.]
   [  0.]
   [  0.]
   [  0.]
   [  0.]
   [  0.]
   [  0.]
   [  0.]
   [  0.]
   [  0.]
   [  0.]
   [  0.]
   [  0.]
   [  0.]
   [  0.]
   [  0.]
   [  0.]
   [  0.]
   [  0.]
   [  0.]
   [  0.]
   [  0.]
   [  0.]
   [  0.]
   [  0.]
   [  0.]
   [  0.]]

  [[  0.]
   [  0.]
   [  0.]
   [  0.]
   [  0.]
   [  0.]
   [  0.]
   [  0.]
   [  0.]
   [  0.]
   [  0.]
   [  0.]
   [  0.]
   [  0.]
   [  0.]
   [  0.]
   [  0.]
   [  0.]
   [  0.]
   [  0.]
   [  0.]
   [  0.]
   [  0.]
   [  0.]
   [  0.]
   [  0.]
   [  0.]
   [  0.]]

  [[  0.]
   [  0.]
   [  0.]
   [  0.]
   [  0.]
   [  0.]
   [  0.]
   [  0.]
   [  0.]
   [  0.]
   [  0.]
   [  0.]
   [  0.]
   [  0.]
   

In [190]:
# import matplotlib.pyplot as plt
# plt.imshow(fashion_mnist.load_data()[0][0][0])

## 모델 생성

In [191]:
model = MyModel()

model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

## 모델 학습

In [ ]:
model.fit(train_ds, validation_data=test_ds, epochs=EPOCHS)

Epoch 1/200
625/625 [==============================] - 17s 27ms/step - loss: 0.4545 - accuracy: 0.9116 - val_loss: 2.3018 - val_accuracy: 0.1034
Epoch 2/200
625/625 [==============================] - 16s 26ms/step - loss: 0.0912 - accuracy: 0.9707 - val_loss: 2.3214 - val_accuracy: 0.1000
Epoch 3/200
625/625 [==============================] - 16s 26ms/step - loss: 0.0556 - accuracy: 0.9805 - val_loss: 2.5793 - val_accuracy: 0.1000
Epoch 4/200
625/625 [==============================] - 16s 25ms/step - loss: 0.0508 - accuracy: 0.9829 - val_loss: 3.3052 - val_accuracy: 0.1000
Epoch 5/200
625/625 [==============================] - 16s 25ms/step - loss: 0.0407 - accuracy: 0.9866 - val_loss: 5.2123 - val_accuracy: 0.1000
Epoch 6/200
625/625 [==============================] - 16s 25ms/step - loss: 0.0350 - accuracy: 0.9891 - val_loss: 9.1277 - val_accuracy: 0.1000
Epoch 7/200
625/625 [==============================] - 16s 26ms/step - loss: 0.0366 - accuracy: 0.9895 - val_loss: 6.1773 - val_ac

In [ ]:
# test_loss, test_acc = model.evaluate(x_test,  y_test, verbose=2)

# print('\nTest accuracy:', test_acc)

In [ ]:
test_df = pd.read_csv(r'C:\Users\6509504\Mnist_number\dataset\sample_submission.csv')
test_dir = r'C:\Users\6509504\Mnist_number\dataset\test\\'
test_file_path = test_dir + test_df['file_name']
print(test_file_path[0])

def dataset_raw (path):
    
    image = Image.open(path) 
    image_array = np.array(image).reshape(784)
    return image_array

test_data = np.array(list(test_file_path.apply(dataset_raw)))

In [141]:
a = test_data.reshape(5000, 28, 28)

In [142]:
probability_model = tf.keras.Sequential([model, tf.keras.layers.Softmax()])

predictions = probability_model.predict(a)


# model.predict(
#     x, batch_size=None, verbose=0, steps=None, callbacks=None, max_queue_size=10,
#     workers=1, use_multiprocessing=False
# )

In [167]:
for i in range(len(test_df['label'])):
    test_df['label'][i] = tf.math.argmax(predictions[i]).numpy()
    

C:\Users\6509504\Anaconda3\envs\tensorflow2\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


In [169]:
test_df.to_csv('submit.csv', index=None)

In [154]:
predictions[3]

array([0.08533674, 0.08533674, 0.08533674, 0.23196931, 0.08533674,
       0.08533674, 0.08533674, 0.08533674, 0.08533674, 0.08533674],
      dtype=float32)

In [170]:
test_df

file_name  label
0     idx0001.png      1
1     idx0002.png      0
2     idx0003.png      8
3     idx0004.png      3
4     idx0005.png      5
5     idx0006.png      9
6     idx0007.png      2
7     idx0008.png      4
8     idx0009.png      5
9     idx0010.png      1
10    idx0011.png      8
11    idx0012.png      7
12    idx0013.png      2
13    idx0014.png      4
14    idx0015.png      3
15    idx0016.png      6
16    idx0017.png      6
17    idx0018.png      5
18    idx0019.png      6
19    idx0020.png      6
20    idx0021.png      4
21    idx0022.png      0
22    idx0023.png      4
23    idx0024.png      4
24    idx0025.png      2
25    idx0026.png      7
26    idx0027.png      2
27    idx0028.png      0
28    idx0029.png      1
29    idx0030.png      4
30    idx0031.png      2
31    idx0032.png      3
32    idx0033.png      8
33    idx0034.png      2
34    idx0035.png      9
35    idx0036.png      3
36    idx0037.png      2
37    idx0038.png      6
38    idx0039.png      1
39    idx0040.png      9
40    idx0041.png      1
41    idx0042.png      6
42    idx0043.png      7
43    idx0044.png      8
44    idx0045.png      9
45    idx0046.png      3
46    idx0047.png      3
47    idx0048.png      3
48    idx0049.png      2
49    idx0050.png      8
50    idx0051.png      0
51    idx0052.png      1
52    idx0053.png      0
53    idx0054.png      5
54    idx0055.png      6
55    idx0056.png      2
56    idx0057.png      0
57    idx0058.png      3
58    idx0059.png      9
59    idx0060.png      0
60    idx0061.png      5
61    idx0062.png      9
62    idx0063.png      8
63    idx0064.png      8
64    idx0065.png      8
65    idx0066.png      2
66    idx0067.png      5
67    idx0068.png      7
68    idx0069.png      8
69    idx0070.png      2
70    idx0071.png      1
71    idx0072.png      1
72    idx0073.png      3
73    idx0074.png      8
74    idx0075.png      1
75    idx0076.png      2
76    idx0077.png      9
77    idx0078.png      8
78    idx0079.png      8
79    idx0080.png      2
80    idx0081.png      5
81    idx0082.png      5
82    idx0083.png      3
83    idx0084.png      8
84    idx0085.png      9
85    idx0086.png      7
86    idx0087.png      2
87    idx0088.png      4
88    idx0089.png      6
89    idx0090.png      8
90    idx0091.png      4
91    idx0092.png      7
92    idx0093.png      7
93    idx0094.png      3
94    idx0095.png      3
95    idx0096.png      4
96    idx0097.png      5
97    idx0098.png      8
98    idx0099.png      0
99    idx0100.png      6
100   idx0101.png      8
101   idx0102.png      7
102   idx0103.png      1
103   idx0104.png      5
104   idx0105.png      0
105   idx0106.png      6
106   idx0107.png      7
107   idx0108.png      9
108   idx0109.png      5
109   idx0110.png      0
110   idx0111.png      9
111   idx0112.png      9
112   idx0113.png      4
113   idx0114.png      0
114   idx0115.png      7
115   idx0116.png      3
116   idx0117.png      1
117   idx0118.png      0
118   idx0119.png      4
119   idx0120.png      7
120   idx0121.png      2
121   idx0122.png      9
122   idx0123.png      7
123   idx0124.png      9
124   idx0125.png      6
125   idx0126.png      1
126   idx0127.png      9
127   idx0128.png      7
128   idx0129.png      3
129   idx0130.png      2
130   idx0131.png      2
131   idx0132.png      4
132   idx0133.png      7
133   idx0134.png      3
134   idx0135.png      6
135   idx0136.png      5
136   idx0137.png      9
137   idx0138.png      3
138   idx0139.png      1
139   idx0140.png      0
140   idx0141.png      4
141   idx0142.png      5
142   idx0143.png      5
143   idx0144.png      1
144   idx0145.png      7
145   idx0146.png      4
146   idx0147.png      1
147   idx0148.png      5
148   idx0149.png      2
149   idx0150.png      0
150   idx0151.png      9
151   idx0152.png      9
152   idx0153.png      2
153   idx0154.png      0
154   idx0155.png      7
155   idx0156.png      5
156   idx0157.png      1
157   idx0158.png      4
158   idx0159.png      2
159   id